### PR TITLE
New apps submission

### PR DESCRIPTION
**Pull request by natrim**
merge when there are enough

### CODE REVIEW

**Comment by quanglam2807** [comment]
@natrim There is a problem with ICO generator code so it would take some time until I can merge this PR.

**Comment by quanglam2807** [comment]
@natrim I have a suggestion for you to find official icon: Use Google Play.

For example, Airdroid:

Go to: https://play.google.com/store/apps/details?id=com.sand.airdroid&hl=en
Get the icon URL: https://lh3.googleusercontent.com/16vTHSEJ9f4CQIKH4wtJ2urNhgY3kwBtyG5gWDRiRmVU2vH2a-8a9l0CQFZOKw2CU_o=w300-rw
Remove `=w300-rw`, boom, you have 512x512px official icon: 
https://lh3.googleusercontent.com/16vTHSEJ9f4CQIKH4wtJ2urNhgY3kwBtyG5gWDRiRmVU2vH2a-8a9l0CQFZOKw2CU_o

**Comment by natrim** [comment]
i am doing it like that, if there is not icon in the submission and if there exist an android app for the link

**Comment by quanglam2807** [comment]
@natrim Are you still up?

**Pull request merged**
