### PR TITLE
Optimize icons

### PR DESCRIPTION
**Pull request by natrim**
optimized icons, saves cca 7MB
to merge after #4

### CODE REVIEW

**Comment by quanglam2807** [comment]
@natrim Do you think this is necessary? Because the system automatically compresses the images. The master branch is only for development.

**Comment by natrim** [comment]
well, its not really needed,
 its just that i hate having big git repos on ssd
 so i have this urge to optimize it

**Comment by quanglam2807** [comment]
@natrim I've planned to build a proper backend soon so we don't need to rely on Git. But it will take some time.

**Comment by quanglam2807** [comment]
@natrim I merged this. But actually, Git still keeps the old ones in the data so :(

**Pull request closed without merging**
