### PR TITLE
New apps submission

### PR DESCRIPTION
**Pull request by natrim**
merge when there are enough

### CODE REVIEW

**Comment by quanglam2807** [comment]
https://www.producthunt.com/posts/new-spotify-web-player

**Comment by natrim** [comment]
i dont there will be some new submission for a whilebeucause of the ability to make custom ones in latest release
so this one is ready to merge

**Comment by quanglam2807** [comment]
@natrim Spotify?

**Comment by natrim** [comment]
oh, thats what that random link was .)

**Comment by natrim** [comment]
@quanglam2807 is ti ok like this or any other needed changes?

**Pull request merged**
