### PR TITLE
some more apps

### PR DESCRIPTION
**Pull request by natrim**

### CODE REVIEW

**Comment by quanglam2807** [comment]
@natrim How can I contact you? Send me an email, please :)

**Comment by natrim** [comment]
@quanglam2807 you already did send me e-mail before :) (its a gmail)

**Comment by quanglam2807** [comment]
@natrim OK, then Hangouts :)

**Comment by quanglam2807** [comment]
@natrim This repo is no longer used :) I'll let you know more details via Hangouts.

**Pull request merged**
